[package]
name = "yarnn-native-blas"
version = "0.1.0"
authors = ["Andrey Tkachenko <andreytkachenko64@gmail.com>"]
edition = "2018"

[dependencies]
openblas-src = {version = "0.7.0", features = ["system"]}
blas = "0.20.0"
cblas = "0.2.0"