[package]
name = "yarnn-example-mnist"
version = "0.1.0"
authors = ["Andrey Tkachenko <andreytkachenko64@gmail.com>"]
edition = "2018"

[dependencies]
mnist = "0.4.0"
yarnn = "0.1.0"
yarnn-model-mnist = "0.1.0"